# Generated by Django 4.1.7 on 2023-03-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapi', '0002_alter_executors_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executors',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='historicalexecutors',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
    ]
