# Generated by Django 4.1.7 on 2023-03-05 09:59

import avtoapi.models
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapi', '0003_alter_executors_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executors',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', validators=[avtoapi.models.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='historicalexecutors',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', validators=[avtoapi.models.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
