# Generated by Django 4.1.7 on 2023-03-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapi', '0005_alter_executors_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltasks',
            name='TaskDesc',
            field=models.TextField(verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='TaskDesc',
            field=models.TextField(verbose_name='Описание задачи'),
        ),
    ]
